# Generated by Django 4.2.6 on 2024-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0002_alter_scraps_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='category',
            field=models.CharField(choices=[('metal', 'metal'), ('plastic', 'plastic'), ('paper', 'paper'), ('electronic', 'electronic'), ('textile', 'textile'), ('glass', 'glass'), ('organic', 'organic'), ('rubber', 'rubber')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
