# Generated by Django 5.0.1 on 2024-03-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0003_alter_scraps_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='scrapimage'),
        ),
    ]
